version: 2.1
jobs:
  build:
    docker:
      - image: caconym1502/tectonic:latest

    steps:
      - checkout

      - run:
          name: pdflatex
          command: tectonic main.tex
          
      # persist artifact to workspace: https://circleci.com/docs/2.0/configuration-reference/#persist_to_workspace
      - store_artifacts:
          path: main.pdf